name: setup-java
description: Setup Amazon Corretto 21
runs:
  using: composite
  steps:
    - name: setup-java
      uses: actions/setup-java@v4.0.0
      with:
        distribution: corretto
        java-version: '21'
    - name: dump-github-context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      shell: bash
      run: echo "$GITHUB_CONTEXT"
    - name: setup-gradle
      uses: gradle/actions/setup-gradle@v3.3.2
      with:
        cache-disable: false