on:
  workflow_dispatch:
    inputs:
      onRollback:
        type: boolean
        required: true
        default: false
        description: "Whether the workflow was triggered on rollback"
permissions:
  actions: write
jobs:
  echo:
    runs-on: ubuntu-22.04
    steps:
      - name: echo
        run: "echo auto-run-check on_rollback: ${{ github.event.inputs.onRollback }}"
      - name: checkout
        uses: actions/checkout@v4.1.3
      - name: gh-workflow-run
        run: gh workflow run auto-run.manual-test.yaml -f onRollback=true
        env:
          GH_TOKEN: ${{ github.token }}
        if: ${{ !inputs.onRollback }}
