on:
  workflow_dispatch:
    inputs:
      onRollback:
        required: true
        default: false
        description: "Whether the workflow was triggered on rollback"
jobs:
  echo:
    runs-on: ubuntu-22.04
    steps:
      - name: echo
        run: "echo auto-run-check (on_rollback: ${{ github.event.inputs.onRollback }})"