on: workflow_dispatch
permissions:
  id-token: write
jobs:
  cdk-ls:
    runs-on: ubuntu-22.04
    steps:
      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: arn:aws:iam::779481764036:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHubAction-${{ github.run_id }}-${{ github.run_number }}
          aws-region: eu-west-1
      - name: sts-get-caller-identity
        run: aws sts get-caller-identity
      - name: npm-install-cdk
        run: npm install -g aws-cdk@2.84.0
      - name: setup-java
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'corretto'
          java-version: '17.0.7.7.1'
      - name: checkout
        uses: actions/checkout@v3.5.3
      - name: cdk-ls
        run: cdk ls