on: workflow_dispatch
permissions:
  id-token: write
  checks: write
jobs:
  cdk-deploy-gradle-test:
    runs-on: ubuntu-22.04
    steps:
      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v3.0.1
        with:
          role-to-assume: arn:aws:iam::779481764036:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHubAction-${{ github.run_id }}-${{ github.run_number }}
          aws-region: eu-west-1
      - name: sts-get-caller-identity
        run: aws sts get-caller-identity
      - name: npm-install-cdk
        run: npm install -g aws-cdk@2.93.0
      - name: checkout
        uses: actions/checkout@v3.6.0
      - name: setup-java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
      - name: cdk-permissions-broadening
        id: cdk-permissions-broadening
        run: cdk diff --security-only --fail | tee cdk-diff-security
        continue-on-error: true
      - uses: actions/upload-artifact@v3.1.2
        if: steps.cdk-permissions-broadening.outcome == 'failure'
        with:
          name: cdk-diff-security
          path: cdk-diff-security
      - name: cdk-deploy
        run: cdk deploy --all --require-approval never
        if: success() || failure()
      - name: assume-test-runner-role
        uses: aws-actions/configure-aws-credentials@v3.0.1
        with:
          role-to-assume: BinsleyTestRunner
          role-chaining: true
          aws-region: eu-west-1
      - name: gradle-test
        run: ./gradlew test
      - name: test-report
        uses: mikepenz/action-junit-report@v3.8.0
        if: success() || failure()
        with:
          report_paths: 'build/test-results/test/TEST-*.xml'