on:
  workflow_dispatch:
    inputs:
      force_rollback:
        type: boolean
        required: true
        default: false
        description: 'Force an immediate rollback'
      prevent_rollback:
        type: boolean
        required: true
        default: false
        description: 'Prevent rollback on workflow failure'
      force_unconditional_execution:
        type: boolean
        required: true
        default: false
        description: 'Force unconditional execution of jobs without Gradle caching'
  push:
    branches:
      - main
    paths-ignore:
      - 'decisions/**'
      - '.github/workflows/*.manual-test.yaml'
  schedule:
    - cron: '30 7 * * 0'
permissions:
  id-token: write
  checks: write
  contents: write # for git rollback
  actions: write # for rollback workflow run
concurrency:
  group: default
  cancel-in-progress: false
jobs:
  force-rollback:
    runs-on: ubuntu-22.04
    if: ${{ inputs.force_rollback }}
    steps:
     - name: force-rollback
       run: |
         echo "Forced rollback" >> $GITHUB_STEP_SUMMARY
         false
  changes:
     runs-on: ubuntu-22.04
     outputs:
       subprojects: ${{ steps.filter.outputs.changes }}
     steps:
     - name: checkout
       uses: actions/checkout@v4.1.6
     - uses: dorny/paths-filter@v3.0.2
       id: filter
       with:
         filters: |
           WorkflowMetrics: "**"
     - run: echo "stacks=$(jq -c '. | map(. + "*")' <<< ${{ steps.filter.outputs.changes }})" >> $GITHUB_OUTPUT
  cdk-deploy:
    environment: test
    runs-on: ubuntu-22.04
    needs: [force-rollback, changes]
    if: ${{ !cancelled() && needs.force-rollback.result == 'skipped' && needs.changes.outputs.subprojects != '' && toJson(fromJson(needs.changes.outputs.subprojects)) != '[]' }}
    steps:
      - name: aws-assume-role
        uses: hertzsprung/binsley/actions/aws-assume-role@main
        with:
          account-id: ${{ vars.AWS_ACCOUNT_ID }}
      - name: npm-install-cdk
        run: npm install -g aws-cdk@2.142.1
      - name: checkout
        uses: actions/checkout@v4.1.6
      - name: setup-java
        uses: hertzsprung/binsley/actions/setup-java@main
        with:
          force_unconditional_execution: ${{ inputs.force_unconditional_execution }}
      - name: cdk-permissions-broadening
        id: cdk-permissions-broadening
        run: cdk diff --security-only --fail "${{ needs.changes.outputs.stacks }}" > cdk-diff-security
        continue-on-error: true
      - name: cdk-diff-security
        id: cdk-diff-security
        uses: actions/upload-artifact@v4.3.3
        if: ${{ !cancelled() && steps.cdk-permissions-broadening.outcome == 'failure' }}
        with:
          name: cdk-diff-security
          path: cdk-diff-security
      - name: cdk-deploy
        run: cdk deploy --require-approval never "${{ needs.changes.outputs.stacks }}"
        if: ${{ !cancelled() && (steps.cdk-permissions-broadening.outcome == 'success' || steps.cdk-permissions-broadening.outcome == 'failure') }}
  test:
    uses: ./.github/workflows/test.yaml
    needs: cdk-deploy
    if: always() && !cancelled() && !failure() # https://github.com/actions/runner/issues/491#issuecomment-1507495166
    with:
      environment: test
  rollback:
    runs-on: ubuntu-22.04
    needs: [force-rollback, cdk-deploy, test]
    if: ${{ always() && !cancelled() && contains(needs.*.result, 'failure') && !inputs.prevent_rollback }}
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 2
          token: ${{ secrets.ROLLBACK_TOKEN }}
      - name: git-rollback
        shell: bash
        run: |
          branch_name="rollback-$(printf '%(%Y-%m-%d_%H.%M.%S)T\n')"
          git config user.name 'Binsley GitHub Actions'
          git config user.email 'hertzsprung+binsley@users.noreply.github.com'
          git branch $branch_name
          git checkout main
          git reset --hard HEAD~1
          git push origin main --force
          git push --set-upstream origin $branch_name
      - name: gh-workflow-run
        shell: bash
        run: gh workflow run default.yaml -f prevent_rollback=true
        env:
          GH_TOKEN: ${{ github.token }}
