on: workflow_dispatch
permissions:
  id-token: write
jobs:
  cdk-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          role-to-assume: arn:aws:iam::779481764036:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHubAction-${{ github.run_id }}-${{ github.run_number }}
          aws-region: eu-west-1
      - name: sts-get-caller-identity
        run: aws sts get-caller-identity
      - name: npm-install-cdk
        run: npm install -g aws-cdk@2.84.0
      - name: checkout
        uses: actions/checkout@v3.5.3
      - name: setup-java
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
      - name: cdk-permissions-broadening
        id: cdk-permissions-broadening
        run: cdk diff --security-only --fail > cdk-diff-security
        continue-on-error: true
      - uses: actions/upload-artifact@v3.1.2
        if: steps.cdk-permissions-broadening.outcome == 'failure'
        with:
          name: cdk-diff-security
          path: cdk-diff-security
      - name: cdk-deploy
        run: cdk deploy --require-approval never
        if: success() || failure()