on: workflow_dispatch
jobs:
  self-modify:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.2
        with:
          token: ${{ secrets.ROLLBACK_TOKEN }}
      - name: git-push
        run: |
          echo "#" >> .github/workflows/self-modify.manual-test.yaml
          git config user.name 'Binsley GitHub Actions'
          git config user.email 'binsley@users.noreply.github.com'
          git add .github/workflows/self-modify.manual-test.yaml
          git commit -m "self-modify.manual-test.yaml"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.ROLLBACK_TOKEN }}
