on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
        default: test
        description: "GitHub Actions deployment environment"
permissions:
  id-token: write
  checks: write
jobs:
  test:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.1
    - name: setup-java
      uses: actions/setup-java@v3.13.0
      with:
        distribution: 'corretto'
        java-version: '21'
        cache: 'gradle'
    - name: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v4.0.1
      with:
        role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GitHubActions"
        role-session-name: GitHubActions-${{ github.run_id }}-${{ github.run_number }}
        aws-region: eu-west-1
    - name: gradle-test
      id: gradle-test
      run: ./gradlew test
    - name: test-report
      uses: mikepenz/action-junit-report@v4.0.3
      if: ${{ !cancelled() && (steps.gradle-test.outcome == 'success' || steps.gradle-test.outcome == 'failure') }}
      with:
        report_paths: 'build/test-results/test/TEST-*.xml'